server:
  port: ${PORT:8080}

spring:
  application:
    name: agenda-pro-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# =========================
# JWT (autenticação)
# =========================

jwt:
  secret: ${JWT_SECRET:minha_chave_super_secreta_123456789}
  expiration: ${JWT_EXPIRATION:86400000} # 1 dia em ms

# =========================
# LOGGING
# =========================

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE